#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-python-memcached
Version  : 1.59
Release  : 44
URL      : http://pypi.debian.net/python-memcached/python-memcached-1.59.tar.gz
Source0  : http://pypi.debian.net/python-memcached/python-memcached-1.59.tar.gz
Summary  : Pure python memcached client
Group    : Development/Tools
License  : Python-2.0
Requires: deprecated-python-memcached-python = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : six
BuildRequires : six-python

%description
[![Build
Status](https://travis-ci.org/linsomniac/python-memcached.svg)](https://travis-ci.org/linsomniac/python-memcached)

%package legacypython
Summary: legacypython components for the deprecated-python-memcached package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-python-memcached package.


%package python
Summary: python components for the deprecated-python-memcached package.
Group: Default

%description python
python components for the deprecated-python-memcached package.


%prep
%setup -q -n python-memcached-1.59

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554326974
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
